version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sandbox-topic:1:1"
    volumes:
      -  ${PWD}/volume/var/run/docker.sock:/var/run/docker.sock
  mysql:
    image: mysql:5.7.16
    container_name: mysqlPractContainer
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=welcome
      - MYSQL_DATABASE=sales
      - MYSQL_USER=honkydonky
      - MYSQL_PASSWORD=p_ssW0rd
    command: >
      --server-id=857
      --log-bin=binlog
      --binlog_format=ROW
      --binlog_row_image=FULL
      --gtid_mode=ON
      --enforce-gtid-consistency=ON
    volumes:
      - ${PWD}/volume/mysqldata:/var/lib/mysql
      - ${PWD}/scripts/sales:/docker-entrypoint-initdb.d
  canal-server:
    image: canal/canal-server:latest
    container_name: canal_server
    ports:
      - "11111:11111"
    volumes:
      - ${PWD}/scripts/instance.properties:/home/admin/canal/conf/example/instance.properties
    environment:
      # Set the mode, 'tcp' is default, can also be 'kafka', etc.
      canal.serverMode: tcp
    depends_on:
      - mysql
  connect:
    image: quay.io/debezium/connect:2.7
    container_name: container_kafka_connect
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: kafka_connect_configs
      OFFSET_STORAGE_TOPIC: kafka_connect_offsets
      STATUS_STORAGE_TOPIC: kafka_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9093
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    depends_on:
      - zookeeper
      - kafka
      - mysql
  spark-master:
    image: bitnami/spark:3.5.0 # Use a specific, stable version
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077" # Master RPC port
      - "8080:8080" # Master Web UI port

  spark-worker-1:
    image: bitnami/spark:3.5.0
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - "8081:8081" # Worker 1 Web UI port
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888" # Jupyter Lab UI port
    volumes:
      # Mount a local 'notebooks' directory for your work
      - ./notebooks:/home/jovyan/work
    environment:
      - PYSPARK_PYTHON=python
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
